# This file was generated for 64-bit Windows platforms,
# some dependencies have different versions than the official ones used on unix systems 
# and some dependencies are not available in any version until the date of creation of this file

name: mobenv-virtualenv
channels:
  - conda-forge
  - defaults
platforms:
  - win-64
dependencies:
  - asgiref=3.5.2
  - blas=1.0
  - bzip2=1.0.8
  - ca-certificates=2024.3.11
  - django=4.1
  - expat=2.6.2
  - libcxx=7.0.0
  - libffi=3.4.4
  - libgfortran=14.1.0
  - libgfortran5=14.1.0
# - libopenblas=0.3.27 // This dependence generates conflict with other
  - llvm-openmp=18.1.8
# - ncurses=6.4 // Not available in any Windows-OS version
  - networkx=3.2.1
  - numpy=1.26.4
  - numpy-base=1.26.4
  - openssl=3.0.14
  - packaging=23.2
  - pip=24.0
  - plotly=5.22.0
  - python=3.12.4
  - pyyaml=6.0.1
# - readline=8.2 // Not available in any Windows-OS version
  - setuptools=69.5.1
  - sqlite=3.45.3
  - sqlparse=0.4.4
  - tenacity=8.2.2
  - tk=8.6.14
  - tzdata=2024a
  - wheel=0.43.0
  - xz=5.4.6
  - yaml=0.2.5
  - zlib=1.2.13
