name: mobenv
channels:
  - pyg
  - pytorch
  - conda-forge
  - defaults
dependencies:
  - _openmp_mutex
  - aiohappyeyeballs
  - aiohttp
  - aiosignal
  - altgraph
  - asgiref
  - asttokens
  - attrs
  - backports.zoneinfo
  - blas
  - brotli
  - brotli-bin
  - brotli-python
  - bzip2
  - ca-certificates
  - cairo
  - certifi
  - cffi
  - channels
  - charset-normalizer
  - colorama
  - comm
  - contourpy
  - cpuonly
  - cpython
  - cycler
  - debugpy
  - decorator
  - deprecated
  - dill
  - django
  - django-cors-headers
  - djangorestframework
  - double-conversion
  - exceptiongroup
  - executing
  - expat
  - filelock
  - font-ttf-dejavu-sans-mono
  - font-ttf-inconsolata
  - font-ttf-source-code-pro
  - font-ttf-ubuntu
  - fontconfig
  - fonts-conda-ecosystem
  - fonts-conda-forge
  - fonttools
  - freetype
  - frozenlist
  - fsspec
  - fst-pso
  - future
  - fuzzytm
  - gensim
  - graphite2
  - h2
  - harfbuzz
  - hpack
  - hyperframe
  - icu
  - idna
  - importlib-metadata
  - importlib-resources
  - importlib_resources
  - intel-openmp
  - ipykernel
  - ipython
  - jedi
  - jinja2
  - joblib
  - jupyter_client
  - jupyter_core
  - kiwisolver
  - krb5
  - lcms2
  - lerc
  - libabseil
  - libblas
  - libbrotlicommon
  - libbrotlidec
  - libbrotlienc
  - libcblas
  - libclang13
  - libcxx
  - libdeflate
  - libexpat
  - libffi
  - libgcc
  - libgfortran
  - libgfortran5
  - libglib
  - libgomp
  - libhwloc
  - libiconv
  - libintl
  - libjpeg-turbo
  - liblapack
  - liblzma
  - libpng
  - libprotobuf
  - libsodium
  - libsqlite
  - libtiff
  - libtorch
  - libuv
  - libwebp
  - libwebp-base
  - libwinpthread
  - libxcb
  - libxml2
  - libxslt
  - libzlib
  - llvm-meta
  - llvm-openmp
  - llvmlite
  - markupsafe
  - matplotlib
  - matplotlib-base
  - matplotlib-inline
  - miniful
  - mkl
  - mkl-service
  - mkl_fft
  - mkl_random
  - mpmath
  - multidict
  - munkres
  - nest-asyncio
  - networkx
  - node2vec
  - numba
  - numpy
  - numpy-base
  - openjpeg
  - openssl
  - opentelemetry-api
  - packaging
  - pandas
  - parso
  - pcre2
  - pefile
  - pickleshare
  - pillow
  - pip
  - pixman
  - platformdirs
  - plotly
  - prompt-toolkit
  - propcache
  - psutil
  - pthread-stubs
  - pure_eval
  - pycparser
  - pyfume
  - pyg
  - pygments
  - pyinstaller
  - pyinstaller-hooks-contrib
  - pyparsing
  - pyside6
  - pysocks
  - python
  - python-dateutil
  - python-tzdata
  - python_abi
  - pytorch
  - pytorch-mutex
  - pytz
  - pywin32
  - pywin32-ctypes
  - pyyaml
  - pyzmq
  - qhull
  - qt6-main
  - requests
  - scikit-learn
  - scipy
  - setuptools
  - simpful
  - six
  - sleef
  - smart_open
  - sqlite
  - sqlparse
  - stack_data
  - sympy
  - tbb
  - tenacity
  - threadpoolctl
  - tk
  - torchaudio
  - torchvision
  - tornado
  - tqdm
  - traitlets
  - typing_extensions
  - tzdata
  - ucrt
  - unicodedata2
  - urllib3
  - utm
  - vc
  - vc14_runtime
  - vs2015_runtime
  - wcwidth
  - wheel
  - win_inet_pton
  - wrapt
  - xorg-libxau
  - xorg-libxdmcp
  - xz
  - yaml
  - yarl
  - zeromq
  - zipp
  - zlib
  - zstandard
  - zstd
