# packages in environment at C:\Users\joaov\anaconda3\envs\mobenv-virtualenv:
#
# Name                    Version                   Build  Channel
_openmp_mutex             4.5                       2_gnu    conda-forge
asgiref                   3.5.2              pyhd8ed1ab_0    conda-forge
blas                      1.0                         mkl    conda-forge
brotli                    1.1.0                hcfcfb64_1    conda-forge
brotli-bin                1.1.0                hcfcfb64_1    conda-forge
bzip2                     1.0.8                hcfcfb64_5    conda-forge
ca-certificates           2024.7.4             h56e8100_0    conda-forge
certifi                   2024.7.4           pyhd8ed1ab_0    conda-forge
colorama                  0.4.6              pyhd8ed1ab_0    conda-forge
contourpy                 1.2.1           py312h0d7def4_0    conda-forge
cycler                    0.12.1             pyhd8ed1ab_0    conda-forge
django                    4.1             py312haa95532_0  
djangorestframework       3.15.1             pyhd8ed1ab_0    conda-forge
expat                     2.6.2                h63175ca_0    conda-forge
fonttools                 4.53.1          py312h4389bb4_0    conda-forge
freetype                  2.12.1               hdaf720e_2    conda-forge
gettext                   0.22.5               h5728263_2    conda-forge
gettext-tools             0.22.5               h7d00a51_2    conda-forge
glib                      2.80.2               h0df6a38_0    conda-forge
glib-tools                2.80.2               h2f9d560_0    conda-forge
gst-plugins-base          1.22.9               h001b923_1    conda-forge
gstreamer                 1.22.9               hb4038d2_1    conda-forge
icu                       70.1                 h0e60522_0    conda-forge
intel-openmp              2023.2.0         h57928b3_50497    conda-forge
jpeg                      9e                   hcfcfb64_3    conda-forge
kiwisolver                1.4.5           py312h0d7def4_1    conda-forge
krb5                      1.20.1               heb0366b_0    conda-forge
lcms2                     2.15                 ha5c8aab_0    conda-forge
lerc                      4.0.0                h63175ca_0    conda-forge
libasprintf               0.22.5               h5728263_2    conda-forge
libasprintf-devel         0.22.5               h5728263_2    conda-forge
libbrotlicommon           1.1.0                hcfcfb64_1    conda-forge
libbrotlidec              1.1.0                hcfcfb64_1    conda-forge
libbrotlienc              1.1.0                hcfcfb64_1    conda-forge
libclang                  15.0.7          default_h3a3e6c3_5    conda-forge
libclang13                15.0.7          default_hf64faad_5    conda-forge
libcxx                    7.0.0             h1ad3211_1002    conda-forge
libdeflate                1.17                 hcfcfb64_0    conda-forge
libexpat                  2.6.2                h63175ca_0    conda-forge
libffi                    3.4.4                hd77b12b_1  
libgcc                    14.1.0               h1383e82_0    conda-forge
libgettextpo              0.22.5               h5728263_2    conda-forge
libgettextpo-devel        0.22.5               h5728263_2    conda-forge
libgfortran               14.1.0               h719f0c7_0    conda-forge
libgfortran5              14.1.0               hf275ef4_0    conda-forge
libglib                   2.80.2               h0df6a38_0    conda-forge
libgomp                   14.1.0               h1383e82_0    conda-forge
libiconv                  1.17                 hcfcfb64_2    conda-forge
libintl                   0.22.5               h5728263_2    conda-forge
libintl-devel             0.22.5               h5728263_2    conda-forge
libogg                    1.3.5                h2466b09_0    conda-forge
libpng                    1.6.43               h19919ed_0    conda-forge
libsqlite                 3.45.3               hcfcfb64_0    conda-forge
libtiff                   4.5.0                hf8721a0_2    conda-forge
libvorbis                 1.3.7                h0e60522_0    conda-forge
libwebp-base              1.4.0                hcfcfb64_0    conda-forge
libwinpthread             12.0.0.r2.ggc561118da      h57928b3_7    conda-forge
libxml2                   2.12.7               h283a6d9_1    conda-forge
libzlib                   1.2.13               h2466b09_6    conda-forge
llvm-meta                 7.0.0                         0    conda-forge
llvm-openmp               18.1.8               hc790b64_0    conda-forge
matplotlib                3.9.1           py312h2e8e312_0    conda-forge
matplotlib-base           3.9.1           py312h90004f6_0    conda-forge
mkl                       2023.2.0         h6a75c08_50497    conda-forge
mkl-service               2.4.0           py312h2bbff1b_1  
mkl_fft                   1.3.8           py312h2bbff1b_0  
mkl_random                1.2.4           py312h59b6b97_0  
munkres                   1.1.4              pyh9f0ad1d_0    conda-forge
networkx                  3.3                pyhd8ed1ab_1    conda-forge
numpy                     1.26.4          py312hfd52020_0  
numpy-base                1.26.4          py312h4dde369_0  
openjpeg                  2.5.0                ha2aaf27_2    conda-forge
openssl                   3.3.1                h2466b09_2    conda-forge
packaging                 23.2               pyhd8ed1ab_0    conda-forge
pcre2                     10.43                h17e33f8_0    conda-forge
pillow                    10.4.0          py312h827c3e9_0  
pip                       24.0               pyhd8ed1ab_0    conda-forge
plotly                    5.22.0             pyhd8ed1ab_0    conda-forge
ply                       3.11               pyhd8ed1ab_2    conda-forge
pyparsing                 3.1.2              pyhd8ed1ab_0    conda-forge
pyqt                      5.15.9          py312he09f080_5    conda-forge
pyqt5-sip                 12.12.2         py312h53d5487_5    conda-forge
python                    3.12.3          h2628c8c_0_cpython    conda-forge
python-dateutil           2.9.0              pyhd8ed1ab_0    conda-forge
python-tzdata             2024.1             pyhd8ed1ab_0    conda-forge
python_abi                3.12                    4_cp312    conda-forge
pyyaml                    6.0.1           py312h2bbff1b_0  
qhull                     2020.2               hc790b64_5    conda-forge
qt-main                   5.15.8               h720456b_6    conda-forge
setuptools                69.5.1             pyhd8ed1ab_0    conda-forge
sip                       6.7.12          py312h53d5487_0    conda-forge
six                       1.16.0             pyh6c4a22f_0    conda-forge
sqlite                    3.45.3               hcfcfb64_0    conda-forge
sqlparse                  0.4.4              pyhd8ed1ab_0    conda-forge
tbb                       2021.7.0             h91493d7_0    conda-forge
tenacity                  8.2.2              pyhd8ed1ab_0    conda-forge
tk                        8.6.14               h0416ee5_0  
toml                      0.10.2             pyhd8ed1ab_0    conda-forge
tomli                     2.0.1              pyhd8ed1ab_0    conda-forge
tornado                   6.4.1           py312h4389bb4_0    conda-forge
tqdm                      4.66.4             pyhd8ed1ab_0    conda-forge
typing_extensions         4.12.2             pyha770c72_0    conda-forge
tzdata                    2024a                h0c530f3_0    conda-forge
ucrt                      10.0.22621.0         h57928b3_0    conda-forge
vc                        14.3                h8a93ad2_20    conda-forge
vc14_runtime              14.40.33810         ha82c5b3_20    conda-forge
vs2015_runtime            14.40.33810         h3bf8584_20    conda-forge
wheel                     0.43.0             pyhd8ed1ab_1    conda-forge
xz                        5.4.6                h8cc25b3_1  
yaml                      0.2.5                h8ffe710_2    conda-forge
zlib                      1.2.13               h2466b09_6    conda-forge
zstd                      1.5.6                h0ea2cb4_0    conda-forge
