from django.urls import path
from . import views

urlpatterns = [
    path('', views.index),
    path('graph/', views.graph_view, name='graph_view'),
    path('graph/update_graph/', views.update_graph, name='update_graph'),
    path('graph/init_simulation/', views.init_simulation, name='init_simulation'),
    path('graph/run_simulation/', views.run_simulation, name='run_simulation'),
    path('graph/stop_simulation/', views.stop_simulation, name='stop_simulation'),
    path('graph/projects_names/', views.get_projects_names, name='projects_names'),
    path('graph/update_config/', views.update_config, name='update_config'),
    path('graph/get_config_form_layout/',
         views.get_config_form_layout, name='get_config_form_layout'),
    path('graph/add_nodes/', views.add_nodes, name='add_nodes'),
    path('graph/get_config/', views.get_config, name='get_config'),
    path('graph/calculate_degree/',
         views.calculate_degree, name='calculate_degree'),
    path('graph/calculate_diameter/',
         views.calculate_diameter, name='calculate_diameter'),
    path('graph/calculate_eccentricity/',
         views.calculate_eccentricity, name='calculate_eccentricity'),
    path('graph/calculate_shortest_path_between_two_nodes/',
         views.calculate_shortest_path_between_two_nodes, name='calculate_shortest_path_between_two_nodes'),
    path('graph/node2vec_algorithm/',
         views.node2vec_algorithm, name='node2vec_algorithm'),
    path('graph/calculate_distance/',
         views.calculate_distance, name='calculate_distance'),
    path('graph/reevaluate_connections/',
         views.reevaluate_connections, name='reevaluate_connections'),
    path('graph/train_link_prediction/',
         views.train_link_prediction, name='train_link_prediction'),
    path('graph/predict_links/', views.predict_links, name='predict_links'),
    path('graph/train_node_clusterization/',
         views.train_node_clusterization, name='train_node_clusterization'),
    path('graph/train_node_clusterization_dbscan/',
         views.train_node_clusterization_dbscan, name='train_node_clusterization_dbscan'),
    path('graph/train_node_classification/',
         views.train_node_classification, name='train_node_classification'),
    path('graph/classificate_nodes/',
         views.classificate_nodes, name='classificate_nodes'),
    path('graph/network_configuration/1',
         views.network_configuration1, name='network_configuration1'),
    path('graph/network_configuration/2',
         views.network_configuration2, name='network_configuration2'),
    path('graph/network_configuration/3',
         views.network_configuration3, name='network_configuration3'),
    path('graph/network_configuration/4',
         views.network_configuration4, name='network_configuration4'),
    path('graph/network_configuration/5',
         views.network_configuration5, name='network_configuration5'),
    path('graph/network_configuration/6',
         views.network_configuration6, name='network_configuration6'),
    path('graph/network_configuration/7',
         views.network_configuration7, name='network_configuration7'),
    path('graph/network_configuration/8',
         views.network_configuration8, name='network_configuration8'),
    path('graph/network_configuration/9',
         views.network_configuration9, name='network_configuration9'),
    path('graph/network_configuration/10',
         views.network_configuration10, name='network_configuration10'),
]
